targets: 
  $default: 
    sources: 
      - "launcher/lib/**"
      - "launcher/test/**"
      - "$package$"
      - "lib/$lib$"

    builders: 
      flutter_genesis_generator|appCopierBuilder: 
        enabled: true
        generate_for: 
          - "launcher/lib/**"

        options: 
          destinationDirectory: "/Users/becca/StudioProjects/flutter/Work/Adire/flutter_genesis_cli/examples/addd/lib"
          appName: "addd"
          stateManager: "bloc"


      flutter_genesis_generator|appTestCopierBuilder: 
        enabled: true
        generate_for: 
          - "launcher/test/**"

        options: 
          destinationDirectory: "/Users/becca/StudioProjects/flutter/Work/Adire/flutter_genesis_cli/examples/addd/test"
          appName: "addd"
          testPath: "/Users/becca/StudioProjects/flutter/Work/Adire/flutter_genesis_cli/examples/addd/test/"