targets: 
  $default: 
    builders: 
      code_generators|copyBuilder: 
        enabled: false

      code_generators|appBuilder: 
        enabled: true
        generate_for: 
          - "launcher/lib/**"

        options: 
          destinationDirectory: "addd/lib"
          appName: "addd"



    sources: 
      - "launcher/**"
      - "lib/**"