name: flutter_genesis_cli
description: A CLI for starting Flutter projects
version: 0.0.1
homepage: https://github.com/Becca-Saka/flutter_genesis_cli
environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  build: ^2.4.1
  collection: ^1.18.0
  crypto: ^3.0.3
  dio: ^5.4.0
  flutterfire_cli: ^0.2.7
  http: ^0.13.6
  interact: ^2.2.0
  path: ^1.9.0
  sqlite3: ^2.3.0
  tint: ^2.0.1
  uuid: ^4.3.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
