
builders:

  appCopierBuilder:
    import: "package:flutter_genesis_generator/flutter_genesis_generator.dart"
    builder_factories: ["appCopierBuilder"]
    build_extensions: { ".dart": [".gen.dart"] }
    build_to:  source
    auto_apply: root_package
  appTestCopierBuilder:
    import: "package:flutter_genesis_generator/flutter_genesis_generator.dart"
    builder_factories: ["appTestCopierBuilder"]
    build_extensions: { ".dart": [".gen.dart"] }
    build_to:  source
    auto_apply: root_package
