name: flutter_genesis_generator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_config: ^1.1.1
  build_runner: ^2.4.8
