// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcvrYrAp5pxMfHEzAO5XvsT6yHW7mpVvA',
    appId: '1:358276689572:web:08fa6dbbdc2dd91d080031',
    messagingSenderId: '358276689572',
    projectId: 'zappy-a16eeb8e',
    authDomain: 'zappy-a16eeb8e.firebaseapp.com',
    storageBucket: 'zappy-a16eeb8e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIiM8aNDpWz9urt0YXU4K-cMtkFIDrSnw',
    appId: '1:358276689572:android:46949be1fdfdeeef080031',
    messagingSenderId: '358276689572',
    projectId: 'zappy-a16eeb8e',
    storageBucket: 'zappy-a16eeb8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9CLUHFJ1mRojffKFX4COAhrskDH2xHyI',
    appId: '1:358276689572:ios:d7ec699bd023e97d080031',
    messagingSenderId: '358276689572',
    projectId: 'zappy-a16eeb8e',
    storageBucket: 'zappy-a16eeb8e.appspot.com',
    iosBundleId: 'com.example.launcher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9CLUHFJ1mRojffKFX4COAhrskDH2xHyI',
    appId: '1:358276689572:ios:0dd61860adb8a5d9080031',
    messagingSenderId: '358276689572',
    projectId: 'zappy-a16eeb8e',
    storageBucket: 'zappy-a16eeb8e.appspot.com',
    iosBundleId: 'com.example.launcher.RunnerTests',
  );
}
